#!/usr/bin/env bash
# checks if number of arguments equals to zero, else ping 5 times
if [ $# -eq 0 ]; then
    echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
    exit 1
else
    ping -c 5 "$1"
fi
